### ISSUE TITLE
Automatic look for Url in clipboard

### ISSUE THREAD

**Issue by dragonito** [tolry/mental-note#18]
Just a little idea for more comfort

Perhaps it is possible to add links from clipboard automatically to the form when opening it. So you only need to save or tag and save it.

In most cases you copied the link to your clipboard. You can saving some time with this idea. The form could directly search for heading. Thats saving some more time.

**Comment by DavidBadura** [comment]
you can only copy something into the clipboard, not read it. it would be a security issue :wink:

**Comment by tolry** [comment]
Yes, this is not possible, luckily! Every password manager's worst nightmare :smile: 

I agree that this process is repetitive, but unavoidable in the web app. A chrome extension on the other hand would solve this problem *wink

I will close this issue therefore and hope, that we can collaborate on the chrome extension instead?

**Comment by tolry** [comment]
Okay, I've added an "API", if you add a query parameter to the homepage named "add_url" containing the url to add, the "add link" dialog opens automatically. This should make a simple chrome extension fairly easy.

Would you like to work on that, @dragonito ?

**Comment by dragonito** [comment]
+1

**Comment by tolry** [comment]
Great, give me a heads up, if you need my assistance.

**Comment by tolry** [comment]
@dragonito To achieve cleaner separation, I decided to move the add_url functionality into its own controller/route:

* /quick-add?url=....

Sorry for the change, but this is imo a significant improvement (and scrutinizer agrees :wink:) - I promise that this will stay 'stable' from now on.

**Comment by tolry** [comment]
sorry, forgot to reference the commit d5f476b96f6d7cac557d006f2dd163b82592cd19

**Comment by dragonito** [comment]
Thx a lot!

**Comment by dragonito** [comment]
+1

**Comment by tolry** [comment]
Are you working on the extension, can I assist you in any other way on this?

**Comment by dragonito** [comment]
I´ll work on it and i´ll tell you when i begin :)

**Comment by tolry** [comment]
great
