### ISSUE TITLE
Adding empty tags

### ISSUE THREAD

**Issue by dragonito** [tolry/mental-note#20]
It is possible to add empty tags. Have a look here:

![Empty tag](http://g.recordit.co/lVnGrWXQHz.gif)

**Comment by tolry** [comment]
Thanks, I am not sure, if I can prevent select2 from doing this, but I can easily trim the data in php and throw away empty values. If you like, you can give it a shot also.

**Comment by tolry** [comment]
@dragonito issue no longer relevant with new tagging js lib, correct?

**Comment by dragonito** [comment]
Yes,you´re right.
