### ISSUE TITLE
Login Error Message

### ISSUE THREAD

**Issue by dragonito** [tolry/mental-note#32]
You get an error message if you use wrong login data.

`exception 'Symfony\Component\Security\Core\Exception\BadCredentialsException' with message 'Bad credentials.' in /var/www/mental-note/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73 Stack trace: #0 /var/www/mental-note/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php(138): session_start() #1 /var/www/mental-note/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php(259): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->start() #2 /var/www/mental-note/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Session.php(87): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->getBag('attributes') #3 /var/www/mental-note/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ContextListener.php(78): Symfony\Component\HttpFoundation\Session\Session->get('_security_main') #4 /var/www/mental-note/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall.php(69): Symfony\Component\Security\Http\Firewall\ContextListener->handle(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #5 [internal function]: Symfony\Component\Security\Http\Firewall->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #6 /var/www/mental-note/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) #7 /var/www/mental-note/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #8 /var/www/mental-note/var/bootstrap.php.cache(2963): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #9 /var/www/mental-note/var/bootstrap.php.cache(2936): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #10 /var/www/mental-note/var/bootstrap.php.cache(2290): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #11 /var/www/mental-note/web/app.php(28): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #12 {main}`

**Comment by tolry** [comment]
@dragonito thanks for the report

for others who might have the same issue: this comes up when extending an old version of the `login.html.twig` template, see http://stackoverflow.com/questions/26341728/fosuserbundle-badcredentialsexception
