### ISSUE TITLE
Read title / album information from Spotify link

### ISSUE THREAD

**Issue by dragonito** [tolry/mental-note#44]
Is it possible to read some metainformation for entry_title from Spotify link?

**Comment by tolry** [comment]
@dragonito do you have an example URL for testing?

**Comment by tolry** [comment]
nevermind, found a "working url" https://play.spotify.com/track/1P14tkyo4lg26ezcW1g9WI

**Comment by tolry** [comment]
@dragonito should now be working, spotify did send special html for "unsupported" user-agents. I am now mimicking the googlebot, which results in usable html output.

**Comment by dragonito** [comment]
Works great! Thank you!
![works](https://cloud.githubusercontent.com/assets/1980412/23058551/c61776c4-f4f5-11e6-9757-026b34383e2e.png)
