### ISSUE TITLE
Save on Enter

### ISSUE THREAD

**Issue by dragonito** [tolry/mental-note#6]
In Tag-Field: Save link on pressing enter when no new tag is added.

Actually we got: Enter to add a new tag. When no new tag is added nothing happens.

**Comment by DavidBadura** [comment]
i think it is better to use "strg+enter" so you know you submit the form

**Comment by tolry** [comment]
yes, that's annoying right now - ctrl-enter would be a wise choice

"make it so"

**Comment by dragonito** [comment]
+1
